version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fetch-events"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lr0vourewpvz"
s3_prefix = "fetch-events"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
