AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
 fetch-events

 Fetches training events based on start and end date
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  FetchEvents:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fetch-events/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        FetchEventEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fetch-events
            Method: get
            RequestParameters:
              - method.request.querystring.startDate:
                  Required: true
              - method.request.querystring.endDate:
                  Required: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FetchEventsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fetch-events/"
  FetchEvents:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt FetchEvents.Arn
  FetchEventsIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FetchEventsRole.Arn
